### ISSUE TITLE
separation of server.views from the rest of server

### ISSUE THREAD

**Issue by jsms90** [marisid/handlebars-intro-workshop#2]
I may well be wrong about this, and just unaware that this is a regular pattern, but is there any benefit in taking `server.views` away from the rest of the server setup in your solution branch?

i.e. modularising `configure-handlebars.js`, instead of having it in `server.js`?

**Comment by marisid** [comment]
@jsms90 Yes, I think it's quite common to move your config files outside your main server file and this is another abstraction as part of modularised and readable code. It's similar to moving the starting of the server in a separate module `start.js` (this also helps for testing purposes). 

Also, this pattern was something we were shown in our cohort in one of Matt's workshop and I think it's quite neat. Let's say you want to change your templating configuration in the future, all you need to do is editing the config file. But of course, this is not essential for using Handlebars but I thought it would be good to have it there so that they get used to modularisation more with time - it will come in handy when they start working in larger scale projects 😉

**Comment by jsms90** [comment]
Cool. Makes sense.

But still, this seems weird: 
`Handlebars(server)`

Wouldn't it make more sense to use the same pattern as you do with routes? i.e. modularise the configuration options, but not the whole `server.views`. Like you modularise the routes themselves, but don't take out `server.routes` itself.

So in `server.js` you would have:
```javascript
server.register([inert, vision], err => {
  if (err) throw err;
  server.views(configureHandlebars);
  server.route(routes);
});
```

and in `configureHandlebars.js` you would have just:
```javascript
const handlebars = require('handlebars');

module.exports = {
    engines: { hbs: handlebars },
    path: 'views',
    layout: 'default',
    layoutPath: 'views/layout',
    partialsPath: 'views/partials',
    helpersPath: 'views/helpers'
  }
```

**Comment by marisid** [comment]
Done ✔️ - completed-workshop branch is up-to-date now. 
Thanks for you thorough review.
